### ISSUE TITLE
Cookie logger

### ISSUE THREAD

**Issue by kokoshizhsa** [Babyhamsta/Aimmy#1367]
I used aimmy for like 1-2 hours and a bit later steam stuff were gone.. uplay acc, reddit, instagram.. all were changed and some weird posts were made..

**Comment by MarsQQ** [comment]
i’m sorry baby, you are barking at the wrong tree

if you were using Aimmy V1 especially, there is a less than 0% chance of this being a possibility because those versions were source-available and never obfuscated, and if you check the attempted internet connections for Aimmy V2, i’m 99% sure they will only show requests being made to github for the model/config store
