### ISSUE TITLE
[BUG ? ] 

### ISSUE THREAD

**Issue by Catplayz2011** [Babyhamsta/Aimmy#40]
I used the universal modely and when aiaming ant an oponement it was LAGGY ass hell  [every model]

[+] plus i would recommend the future : [Lock until dead/ down]

[+] I created my model and it has 34 game pics. But its ass even my aim was slightly better, anyways, Is that normal should I expect that for just upoading 34 images ?

[+] Now just opening aimmy make my game laggy  I cant even collect data, 2 days ago It wasn't that laggy / it wasn't laggy at all.

Thanks 👍

**Comment by Babyhamsta** [comment]
34 pictures is no where near enough for a model that needs to perform on an FPS. I can tell you our PF model has about 7.5k images and our Universal model has about 12k currently. (New release I have has about 16k).

It isn't possible for us to aim at a person until dead other than training a model or the model to do so as it's full external and we don't access any game data.

V1.1.1 should perform better than 1.0.0, some changes were made to lower resources too and process detections faster. You can try both and see if one works better for you. Unfortunately unless you have a decent CPU/GPU you'll have lower performance, it's due to the nature of the model we use and the processing power needed to do detections.
