### ISSUE TITLE
Huge Program Performance When Changing Models.

### ISSUE THREAD

**Issue by vxzl** [Babyhamsta/Aimmy#80]
## Expected Behavior

Should smoothly be able to change between models.

## Current Behavior

Heavily lags when changing models, if spammed between models for bug finding, heavily lags the system.

## Possible Solution

Check the code for any performance stealing section of the code.

## Steps to Reproduce
1. Click on model. (Happens)
2. If you spam between models, the lag will also occur.

## Context (Environment)

Slows down the program, doesn't affect me heavily but  people with lower-grade devices may crash due to this in the future.

**Comment by RealCalumPlays** [comment]
This is because it is loading the model so this is expected behavior

**Comment by vxzl** [comment]
Yes, but it could be optimized in anyway to stop that, like other software that load stuff like blender, loading models, the opening process is smooth and not low fps, high performance draining if you get me.

**Comment by Babyhamsta** [comment]
This is expected behavior. Loading the models is done via the Onnx Runtime lib, it's as optimized as it can be. Loading it into memory is no small task. It takes less than 2 seconds to load a model, it isn't that big of a deal.

I will look into seeing if there are any settings I can adjust for the lib but I don't believe there will be a fix anytime soon for this issue.
