### ISSUE TITLE
Adding my own .onnx model doesn't work, and when switching to another model breaks entirely.

### ISSUE THREAD

**Issue by Seconb** [Babyhamsta/Aimmy#85]
Hi, I attempted to add a 25k image Fortnite model that I found via another AI aimbot's repo
https://github.com/RootKit-Org/AI-Aimbot/tree/main/customModels/Fortnite
I added the .onnx file but when I enabled it, the model did nothing and when I switched to another model that I knew worked it didn't work. I didn't get frame drops when I activated the aimbot again so I just fucked the AI or smth idk

**Comment by Babyhamsta** [comment]
The reason this doesn't work is because that model is a OnnxV7 and not a OnnxV8 model. They output differently which is why it won't work with Aimmy:

Onnx V7:
![image](https://github.com/Babyhamsta/Aimmy/assets/22938086/26b25012-20a2-4fe6-b61d-5c472ad2fd8f)

Onnx V8:
![image](https://github.com/Babyhamsta/Aimmy/assets/22938086/08b94d21-a20c-4c36-b9ba-b17b65e29adf)

You can view the differences in models via: https://netron.app/
